# Generated by Django 4.2 on 2024-05-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Offshore', '0005_payment_orderplaced'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_order_id',
            new_name='paypal_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_id',
            new_name='paypal_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_payment_status',
            new_name='paypal_payment_status',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('AU', 'Audi'), ('MD', 'Mercedes'), ('BMW', 'BMW'), ('LB', 'Lamborghini'), ('MB', 'Maybach'), ('BT', 'Bentley')], max_length=200),
        ),
    ]
